// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[post].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/log-out.ts";
import * as $5 from "./routes/github/[username].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/log-in.tsx";
import * as $8 from "./routes/subscribe.tsx";
import * as $$0 from "./islands/input.tsx";
import * as $$1 from "./islands/vote-buttons.tsx";

const manifest = {
  routes: {
    "./routes/[post].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/log-out.ts": $4,
    "./routes/github/[username].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/log-in.tsx": $7,
    "./routes/subscribe.tsx": $8,
  },
  islands: {
    "./islands/input.tsx": $$0,
    "./islands/vote-buttons.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
